config/routes.rb
Rails.application.routes.draw do
  resources :guesses
  resources :players
  resources :games

  get "/games/exists/:game_name", to: "games#exists"

  get "/guesses/exists/:slack_id/:guess", to: "guesses#exists"

  get "/players/exists/:slack_id", to: "players#exists"

  get "images/13", to: "images#i13"
  get "images/12", to: "images#i12"
  get "images/11", to: "images#i11"
  get "images/10", to: "images#i10"
  get "images/9", to: "images#i9"
  get "images/8", to: "images#i8"
  get "images/7", to: "images#i7"
  get "images/6", to: "images#i6"
  get "images/5", to: "images#i5"
  get "images/4", to: "images#i4"
  get "images/3", to: "images#i3"
  get "images/2", to: "images#i2"
  get "images/1", to: "images#i1"
  get "images/0", to: "images#i0"

  # post "/slack", to: "slack#get_input"

  # post "/slack", to: "games#create", constraint: SlackCreateGameConstraint.new
  # post "/slack", to: "guesses#update", constraint: SlackGuessConstraint.new
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homepage#show"

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_guess, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /guesses
  # GET /guesses.json
  def index
    @guesses = Guess.all
  end

  # GET /guesses/1
  # GET /guesses/1.json
  def show
  end

  # GET /guesses/new
  def new
    @guess = Guess.new
  end

  # GET /guesses/1/edit
  def edit
  end

  # GET /guesses/exists/slack_id/guess
  def exists

    player_records = Player.find_by(slack_id: "#{params["slack_id"]}")
    
    active_game_id = player_records["active_game"]

    guess_exists = Guess.exists?(game_id: "#{active_game_id}", guess: "#{params["guess"]}")

    game_records = Game.find(active_game_id)
    game_name = game_records["game_name"]

    render :json => {guess_exists: "#{guess_exists}", game_name: "#{game_name}"}

  end

  # POST /guesses
  # POST /guesses.json
  def create

    game_id = params["game_id"]

    guess = params["guess"]

    guess_handler = helpers.generate_guess_handler(game_id,guess)

    @guess = Guess.new({ guess: "#{guess}", game_id: "#{game_id}", correct_or_incorrect: "#{guess_handler.guess_correct?}" })
    
    if @guess.save
      if guess_handler.guess_correct? == 1
        guess_handler.update_word_display
        guess_handler.check_for_win
      else
        guess_handler.update_guessed_letters
        guess_handler.update_lives
        guess_handler.check_for_lose
      end
      render :json => guess_handler.display
    else
      render json: @guess.errors, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /guesses/1
  # PATCH/PUT /guesses/1.json
  def update
    respond_to do |format|
      if @guess.update(guess_params)
        format.html { redirect_to @guess, notice: 'Guess was successfully updated.' }
        format.json { render :show, status: :ok, location: @guess }
      else
        format.html { render :edit }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guesses/1
  # DELETE /guesses/1.json
  def destroy
    @guess.destroy
    respond_to do |format|
      format.html { redirect_to guesses_url, notice: 'Guess was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guess_params
      params.require(:guess).permit(:guess, :game_id, :correct_or_incorrect)
    end
end

app/helpers/guesses_helper.rb
module GuessesHelper
  class GuessHandler
    def initialize(game_id, guess)
      @game_id = game_id
      @guess = guess
    end

    def guess_correct?
      game_records = Game.find(@game_id)
      @word = game_records["word"]
      @word.include?(@guess) ? 1 : 0
    end

    def update_word_display

      correct_guesses = Guess.where(game_id: @game_id, correct_or_incorrect: "1")
      array_of_correct_guesses = correct_guesses.to_a.map! { |entry| entry["guess"] }

      word_display = @word.chars.map do |char| 
        array_of_correct_guesses.include?(char) ? char : '?'
      end.join(" ")

      @game = Game.find(@game_id)
      @game.update(word_display: "#{word_display}")

    end
    
    def update_guessed_letters
      incorrect_guesses = Guess.where(game_id: @game_id, correct_or_incorrect: "0")
      array_of_incorrect_guesses = incorrect_guesses.to_a.map! { |entry| entry["guess"] }

      @game = Game.find(@game_id)
      @game.update(guessed_letters_display: "#{array_of_incorrect_guesses.join(" ")}")
    end

    def update_lives
      @game = Game.find(@game_id)
      lives = @game["lives"] - 1
      @game.update(lives: lives)

    end

    def display
      @game = Game.find(@game_id)
      lives = @game["lives"]
      word_display = @game["word_display"]
      guessed_letters_display = @game["guessed_letters_display"]

      guess_message = @game["status"] == 1 ? "#{guess_correct? == 1 ? "CORRECT" : "INCORRECT" }" : "#{@game["result"] == 1 ? "YOU WIN" : "YOU LOSE"}"

      { lives: lives, guessed_letters_display: guessed_letters_display, word_display: word_display, guess_message: guess_message }
    end

    def check_for_win

      @game = Game.find(@game_id)
      @word_display = @game["word_display"]

      if @word.chars.join(" ") == @word_display
        @game.update( status: "0", result: "1" )
      end

    end

    def check_for_lose

      @game = Game.find(@game_id)
      @lives = @game["lives"]

      if @lives == 0
        @game.update( status: "0", result: "0" )
      end

    end

  end

  def generate_guess_handler(game_id, guess)
    GuessHandler.new(game_id, guess)
  end

end

app/views/guesses/_form.html.erb
<%= form_with(model: guess, local: true) do |form| %>
  <% if guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% guess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guess %>
    <%= form.text_field :guess %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :correct_or_incorrect %>
    <%= form.number_field :correct_or_incorrect %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing Guess</h1>

<%= render 'form', guess: @guess %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guesses</h1>

<table>
  <thead>
    <tr>
      <th>Guess</th>
      <th>Game</th>
      <th>Correct or incorrect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guesses.each do |guess| %>
      <tr>
        <td><%= guess.guess %></td>
        <td><%= guess.game_id %></td>
        <td><%= guess.correct_or_incorrect %></td>
        <td><%= link_to 'Show', guess %></td>
        <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
        <td><%= link_to 'Destroy', guess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<h1>New Guess</h1>

<%= render 'form', guess: @guess %>

<%= link_to 'Back', guesses_path %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Guess:</strong>
  <%= @guess.guess %>
</p>

<p>
  <strong>Game:</strong>
  <%= @guess.game_id %>
</p>

<p>
  <strong>Correct or incorrect:</strong>
  <%= @guess.correct_or_incorrect %>
</p>

<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>